export enum FetchProducts {
  FETCH_LOADING = "FETCH_LOADING",
  FETCH_PRODUCTS = "FETCH_PRODUCTS",
  FETCH_ERROR = "FETCH_ERROR",
  SORT_BY_PRICE_ASCENDING = "SORT_BY_PRICE_ASCENDING",
  SORT_BY_PRICE_WANING = "SORT_BY_PRICE_WANING",
  SORT_BY_ALPHA = "SORT_BY_ALPHA",
  SORT_BY_DEFAULT = "SORT_BY_DEFAULT",
  FILTER_CHECK = 'FILTER_CHECK'
}
